### ISSUE TITLE
ABNotifierReachabilityDidChange always getting FALSE!

### ISSUE THREAD

**Issue by unlucio** [airbrake/airbrake-ios#24]
hello :)
we love your service and we really love to use it but looks like we're unable to get to the crash reporting dialog for some reason :(

We did a little bit of digging and using a the test call from out appdelegate and we found out that log files are written correctly but the ABlib is unable to display the allert dialog and send the notice since it thinks there's no connection :(

PLacing a log here:

``` objc
void ABNotifierReachabilityDidChange(SCNetworkReachabilityRef target, SCNetworkReachabilityFlags flags, void *info) {
    ABLog(@"ABNotifierReachabilityDidChange! flags: %u", flags);
[...]
```

the result is:

```
2013-01-09 16:53:29.942 Save The Mom[3705:707] [Airbrake] ABNotifierReachabilityDidChange! flags: 0
```

and

``` objc
    if ([ABNotifier isReachable:flags]) 
```

is always false, causing the whole thing to not to work :(
Commenting the if, makes things works but, well, "might" not be the best idea ;)

Any idea on how this may happen?

tested on: iphone 4 (5.1.1), iphone 5 (6.0.1) and simulators

**Comment by mandyedi** [comment]
Hi,
I have the same issue. Currently I'm using the quick fix with commenting the if, but I'll dig into the problem and hopefully come up with proper solution.

**Comment by jocelynlih** [comment]
@mandyedi can you share what device and iOS version are you on?

**Comment by mandyedi** [comment]
iPhone 5c with iOS 9.1
