### ISSUE TITLE
Give option to collect user feedback and new design.

### ISSUE THREAD

**Issue by benarent** [airbrake/airbrake-ios#35]
![2](https://f.cloud.github.com/assets/559288/2105691/4e2405b8-8f92-11e3-93d5-aadd5cc39ccb.jpg)
![3](https://f.cloud.github.com/assets/559288/2105692/511fb4e2-8f92-11e3-8ea7-18abda1cfc36.jpg)
![3](https://f.cloud.github.com/assets/559288/2105693/54c642fa-8f92-11e3-96dc-e1351b7587c5.jpg)
![photoshop-2014-02-06-at-6 01 23-pm](https://f.cloud.github.com/assets/559288/2105694/54d45f20-8f92-11e3-824c-074b77ed8374.png)

**Comment by scottbarrow** [comment]
👍
