### ISSUE TITLE
Why is the project ID hard coded in ABNotifier.h?

### ISSUE THREAD

**Issue by boxofrad** [airbrake/airbrake-ios#51]
We've had a lot of issues setting this library up with RubyMotion, one of which was the fact that the Project ID was hard coded in a header file (hence we had to manually vendor the CocoaPod).

Could you please shed some light on why the Project ID is hard coded? (as apposed to say an argument to `startNotifierWithAPIKey`)

Thanks :heart:

**Comment by boxofrad** [comment]
Doesn't this mean that every user of the library would need to edit it's source / the header file?

Could this not be moved to a constructor argument instead?

**Comment by jocelynlih** [comment]
V4.2 add productID as parameter in ABNotifier class method. :)
