### ISSUE TITLE
Not receiving crash report after server gives 201

### ISSUE THREAD

**Issue by johndoran** [airbrake/airbrake-ios#53]
Hi,
We are getting crashed in our app. I have sent an email support ticket with some extra specifics to the app, id's etc.
- the crash is being logged to plcrashreporter
- I open the app and debug as far as it sends the report to to your system
- I see a 201 back in the api response with an id of 1300859853055963762
- No crash reported in the backend system, no emails

Details:
Latest sdk - running iOS7
Crash type - sigbart, call [nsurldatauploadtask resume] when the state of the task is complete triggers this in iOS7.
Occurrences - more the 10

Hope you can help.
John.

**Comment by DanielFontes** [comment]
Same here, the only thing i get is:

Notice ... was rejected: iosutil: cannot parse binary image: "...".

**Comment by jocelynlih** [comment]
Thanks for letting us know and we will look into this issue.

**Comment by mgv** [comment]
I'm getting a similar error. 

```
[Airbrake] Crash report posted status code:201
[Airbrake] {"id":"1358796744996350696","url":"https://airbrake.io/locate/1358796744996350696"}
```
However, accessing the notice's URL shows that the notice is being tagged as rejected:

```
Notice 1358796744996350696 was rejected: iosutil: cannot parse binary image: "       0x10000c000 -        0x100637fff +XXXXX. arm64  <71cc19abe2a63fe5bd84a96c2c983a28> /private".
```

I'm using the latest release (4.1.3) and running on iOS 8.1.

**Comment by nfox513** [comment]
I'm getting the same thing. Triggering a crash using `ABNotifier.writeTestNotice()` does give a crash but throwing an exception in the app does not.

The URL given after uploading the crash report says:
`Notice 1420478912721572327 was rejected: iosutil/report: cannot parse empty string.`

You can see this error from the url: https://airbrake.io/locate/1420478912721572327
