### ISSUE TITLE
iOS 8.3 - UIAlert

### ISSUE THREAD

**Issue by benarent** [airbrake/airbrake-ios#56]
Under Apple iOS 8.3 the UIAlert you are sending to ask people to submit crash reports are not working anymore, meaning they crash the entire app. Since Apple deprecated the UIAlert in iOS8.3 for all users this is a HUGE bug from your side that will crash all Apps that use your library under iOS8.3

**Comment by mmcdaris** [comment]
Assigned to [Tender discussion #39027](http://help.airbrake.io/discussions/problems/39027-ios-83-uialert).

**Comment by jocelynlih** [comment]
Fixed in V4.2
