### ISSUE TITLE
Not building on Xcode 7 and iOS 9+

### ISSUE THREAD

**Issue by s6joui** [airbrake/airbrake-ios#68]
Hi. My app fails to build because the library seems outdated. This is the error:

```
.../Airbrake/CrashReporter.framework/CrashReporter(libCrashReporter-iphoneos.a-armv7-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have tried enabling or disabling bitcode in my build settings but it doesn't make a difference.

**Comment by nigarcia88** [comment]
Any news? 2 months have passed and this error is still showing up.

**Comment by andrecrts** [comment]
any solutions?

**Comment by jocelynlih** [comment]
Please disable bitcode in the build settings for now.
<img width="823" alt="image 2016-02-19 at 9 40 32 am" src="https://cloud.githubusercontent.com/assets/331172/13183758/3d27776e-d6ed-11e5-8960-82bd0ec1f242.png">

**Comment by kaluznyo** [comment]
Any plan to support bitcode ?

**Comment by jocelynlih** [comment]
Yes, it's under testing and will post an update here when it's ready to release.

**Comment by hlung** [comment]
still no update?

**Comment by jocelynlih** [comment]
Sorry about the delay. About bitcode support, this project does use a framework CrashReporter.framework which does not support bitcode. 
A possible workaround is to create a separate pod for Airbrake iOS framework and handle the bitcode support.
For this pod,  please set Enable Bitcode to NO for now.

**Comment by damionvega** [comment]
Still have the same issue after setting Enable Bitcode to "NO"

**Comment by jocelynlih** [comment]
@damionvega can you confirm either in Objective C or Swift project? If you have a failed sample project, I can take a look directly.

**Comment by damionvega** [comment]
Swift

**Comment by damionvega** [comment]
@jocelynlih I made this. It won't run for me. https://github.com/damionvega/sample-swift

**Comment by jocelynlih** [comment]
@damionvega I'm able to build without error after Disable BitCode in both App target and Pod target
<img width="1023" alt="appdisablebitcode" src="https://cloud.githubusercontent.com/assets/331172/23493327/d141dfac-febf-11e6-89a7-27b967296c49.png">
<img width="1022" alt="poddisablebitcode" src="https://cloud.githubusercontent.com/assets/331172/23493328/d15d6fec-febf-11e6-8958-14fbeb0f6440.png">

Let me know if you run into any issue. 
FYI, for the pod build setting change, you can also automatic it by adding a post build script in Podfile 
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
`

**Comment by damionvega** [comment]
Is that the only thing you changed? How were you able to access the Pods project build settings? I have it on my other project, but not the sample app.

**Comment by damionvega** [comment]
OK it's working on my original project. I was only disabling Bitcode on the pod, not on my project as well. Thank you for your help!

P.S. I also had to implement this (https://github.com/airbrake/airbrake-ios/issues/58#issuecomment-224301407):

```
//
//  ABCrashReport.h
//  Hoptoad Sample
//
//  Created by Jocelyn Harrington on 8/14/14.
//
//

#import <Foundation/Foundation.h>
//#import <CrashReporter/CrashReporter.h>
#import "CrashReporter.h"

@interface ABCrashReport : NSObject
@property (nonatomic, strong) PLCrashReporter *plCrashReporter;
+(ABCrashReport *)sharedInstance;
-(void)startCrashReport;
-(NSString *)crashReportStringFormat:(PLCrashReport *)report;
@end
```
