### ISSUE TITLE
Outdated Airbrake Notifier warnings

### ISSUE THREAD

**Issue by arjunsharma** [airbrake/airbrake-ios#69]
I'm using the latest version of airbrake-ios, but my Airbrake emails have the following header:

> This project is using an outdated version of the Airbrake Notifier (). You can upgrade to the latest version (1.3.1) from GitHub or RubyGems.

Is this expected?

**Comment by jocelynlih** [comment]
Hi this is not expected, 
Our current version should be 4.2.4
Can you share your pod file related to Airbrake-iOS?

**Comment by arjunsharma** [comment]
Unfortunately I can't share any information or code related to my project.

I had also opened an issue at http://help.airbrake.io/discussions/ios-notifier and received this reply from someone named Thom:

"Thanks for letting us know. This is a bug. Only users on very old our Rails gem should see that alert. I'll file a bug report for our development team. Let us know if you have any other questions."

**Comment by jocelynlih** [comment]
Thx, it's not an airbrake-iOS issue but airbrake-app bug and there is an internal bug report has been filed with our developers.
Will close this one.
