### ISSUE TITLE
Add context/notifier payload

### ISSUE THREAD

**Issue by kyrylo** [airbrake/airbrake-ios#70]
Apparently this notifier doesn't send `context/notifier` information (nor `notifier` payload):

```
 "notifier": {
      "name": "notifier name",
      "version": "notifier version",
      "url": "notifier url"
    },
```

We should support it to comply with the API v3: https://airbrake.io/docs/#create-notice-v3

**Comment by jocelynlih** [comment]
@kyrylo will add this in next release. 
what's a good url for iOS notifier?

**Comment by kyrylo** [comment]
Thanks, @jocelynlih. The https://github.com/airbrake/airbrake-ios URL should be good.

**Comment by jocelynlih** [comment]
Done.

**Comment by kyrylo** [comment]
@jocelynlih would it be possible to release that addition? I assume next version of the library is 4.2.5, isn't it?

**Comment by jocelynlih** [comment]
Sure. I was working on another issue, since the pending feature is not ready, will do a release today.
