### ISSUE TITLE
Not building in Xcode 7 due to "3 duplicate symbols for architecture x86_64" .

### ISSUE THREAD

**Issue by mpjmarshall** [airbrake/airbrake-ios#76]
This appears to be a linker error.

![screen shot 2016-11-30 at 9 54 05 am](https://cloud.githubusercontent.com/assets/5495278/20759697/47a83d5a-b6e3-11e6-813d-7fd3b7db1f95.png)

This was installed using the pod and is version 4.2.6, I've been trying to find the duplicate but have had zero luck.

**Comment by jocelynlih** [comment]
@mpjmarshall Are you on a Swift project? 
Just tried Obj-C with Xcode 7.3 with pod 'Airbrake-iOS' and has no issue building.

**Comment by mpjmarshall** [comment]
This is an Objective-C project.

**Comment by mpjmarshall** [comment]
We were able to get it working. I may have had a file duplicated somewhere. I did have a question about ProjectID though. Should I ask this question through the support email ?

**Comment by kyrylo** [comment]
@mpjmarshall if it's a general question, then the support email would be the right place.
