### ISSUE TITLE
error in __connection_block_invoke_2: Connection interrupted

### ISSUE THREAD

**Issue by queli1990** [airbrake/airbrake-ios#78]
It runs ok on simulator,but not work iphone.

**Comment by jocelynlih** [comment]
Does this sound like what you're experiencing? https://forums.developer.apple.com/thread/28367
Also do you have see this error without airbrake installed in your app?

**Comment by queli1990** [comment]
this is my iphone's question

**Comment by xzwgithub** [comment]
how did you solve the problem ? I also  meet the problem, and the app'interface could not be clicked
