### ISSUE TITLE
Out of date README

### ISSUE THREAD

**Issue by kyrylo** [airbrake/airbrake-ios#79]
Description by @sgubler from https://github.com/airbrake/airbrake-docs/issues/59

> The README.md is out of date for installing/using Airbrake on iOS 10/Xcode 8 and Cocoapods 1.1.1
>
> Firstly ABCrashReporter.h need the second import statement changed to #import "CrashReporter.h"
>
> Secondly the AppDelegate.swift syntax is:
>
> ABNotifier.start(withAPIKey: "API Key", projectID: "Project ID", environmentName: > ABNotifierAutomaticEnvironment, useSSL: true)

**Comment by jocelynlih** [comment]
Ok, will add the Swift 2.3 and Swift 3.0 instruction in the next release.

**Comment by jocelynlih** [comment]
Updated Readme in 4.2.7
