### ISSUE TITLE
Notice not posted successfully because "Request body too large"

### ISSUE THREAD

**Issue by hboon** [airbrake/airbrake-ios#82]
I'm using RubyMotion and while `writeTestNotice` works, a real crash generates a crash log size of the order of 82k. Looking at https://airbrake.io/docs/api/#create-notice-v3, it appears that the limit is 64kb. Is there a way around this?

**Comment by kyrylo** [comment]
Unfortunately, airbrake-ios doesn't support payload truncation. This is what we usually do to crashes that exceed that limit. We take a notice and strip extra information until it fits the limit.
