### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by Cris-Burlamaqui** [airbrake/airbrake-ios#83]
I've installed the airbrake-io version 4.1.3 and when I try to use it I can't even call any airbrake method because of this architecture issue.
I've tried to change the architecture but the issue remains.

<img width="808" alt="screen shot 2017-06-30 at 12 35 07" src="https://user-images.githubusercontent.com/22418133/27734296-2a7948a4-5d92-11e7-8945-4eb4a574c258.png">

**Comment by jocelynlih** [comment]
@Cris-Burlamaqui Hi, the latest version is 4.2.7 if you are using cocoapod. Can you try the new version?

**Comment by Cris-Burlamaqui** [comment]
Hi, I've tried to update and I couldn't. Now I'm using the version 4.2.6.


<img width="596" alt="screen shot 2017-07-07 at 10 03 24" src="https://user-images.githubusercontent.com/22418133/27951717-c2053604-62fd-11e7-90ec-23a666014ec7.png">

**Comment by jocelynlih** [comment]
not sure what's the format in your Podfile but can't reproduce this issue here. 

Here is my pod file for example:
pod 'Airbrake-iOS', '~>4.2.7'

or simply
pod 'Airbrake-iOS'

More details https://guides.cocoapods.org/using/pod-install-vs-update.html

**Comment by Cris-Burlamaqui** [comment]
Here is my Podfile:

<img width="1105" alt="screen shot 2017-07-10 at 10 51 47" src="https://user-images.githubusercontent.com/22418133/28012686-85fc3ee2-655e-11e7-8d5c-9acd66015b64.png">

**Comment by Cris-Burlamaqui** [comment]
Here is my Podfile:

<img width="648" alt="screen shot 2017-07-10 at 10 54 25" src="https://user-images.githubusercontent.com/22418133/28012809-e5503b3c-655e-11e7-991d-0264ebbf1474.png">

**Comment by Cris-Burlamaqui** [comment]
I'll put here some details about the implementation of Airbrake into my project.

1 - I've installed the Airbrake by Cocoapods and in my "Other Linker Flags" settings are like this:
<img width="1105" alt="screen shot 2017-07-10 at 10 51 47" src="https://user-images.githubusercontent.com/22418133/28012955-62c7e452-655f-11e7-9b6d-06d09a43a5a8.png">

2 - I've imported the ABNotifier class into my AppDelegate.h and I'm using ABNotifierDelegate on the same file.

3 - Inside the AppDelegate.m file I'm calling the method bellow:
[ABNotifier startNotifierWithAPIKey:@"my project key" projectID:@"my project ID" environmentName:ABNotifierAutomaticEnvironment useSSL:YES delegate:self];

Although the same architecture issue still happens.

**Comment by jocelynlih** [comment]
Not sure how but your linker flags are incorrect. From the above screenshot, there are two "Airbrake-iOS" framework listed. There should be only one: -l"Airbrake-iOS"

Please see my screenshot for example:
<img width="745" alt="linker" src="https://user-images.githubusercontent.com/331172/28047862-f8c86c6e-65a1-11e7-836e-d8dcd6f1e5d0.png">

Hopefully this will fix your issue.

**Comment by Cris-Burlamaqui** [comment]
My linker flags is the same as yours just the exhibition in my Xcode is different, however I printed the implementation in my linker flags.

<img width="1105" alt="screen shot 2017-07-11 at 09 15 43" src="https://user-images.githubusercontent.com/22418133/28058925-400d4450-661a-11e7-9681-12538f6b2fd0.png">


<img width="951" alt="screen shot 2017-07-11 at 09 16 31" src="https://user-images.githubusercontent.com/22418133/28058929-45f47226-661a-11e7-901c-8248f8bc4cec.png">

**Comment by jocelynlih** [comment]
@Cris-Burlamaqui go to the row "Any Architecture | Any SDK", delete the row. Right now it's only showing -ObjC, which is incorrect.  
You should be good to go.

**Comment by Cris-Burlamaqui** [comment]
@jocelynlih It worked, thanks for your help.
