### ISSUE TITLE
Ios Airbrake not sending crash to server

### ISSUE THREAD

**Issue by giantslogik** [airbrake/airbrake-ios#85]
I can't get ios airbrake to work, i have integrated as per the docs:

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
[ABNotifier startNotifierWithAPIKey:@"xxxxxxx"
projectID:@"xxxxx"
environmentName:ABNotifierAutomaticEnvironment
useSSL:YES
delegate:self]; 
[ABNotifier writeTestNotice];
return YES;
}

i see airbrake starting up in the logs

2017-08-04 20:44:34.867 SimpleBills[1271:12867] [Airbrake] Notifier 4.2.6 ready to catch errors
2017-08-04 20:44:35.054 SimpleBills[1271:12867] [Airbrake] Environment "Development"

stepping through the writeTestNotice i see airbrake create a dump to a file.

However nothing is sent to server.

**Comment by giantslogik** [comment]
After debugging i have concluded that  the following code fails to display an alert view
        [[[UIApplication sharedApplication] delegate].window.rootViewController presentViewController:alert animated:YES completion:nil];
in ABNotifier.m

Only workaround was to always send the crash dump
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"AlwaysSendCrashReports"];
    [ABNotifier startNotifierWithAPIKey:@"xxxxxxxx"
                              projectID:@"xxxxxx"
                        environmentName:ABNotifierAutomaticEnvironment
                                 useSSL:YES
                               delegate:self];
    [ABNotifier writeTestNotice];
    return YES;
}

**Comment by jocelynlih** [comment]
@giantslogik you can opt out the alert display by using this method:
+ (void)startNotifierWithAPIKey:(NSString *)key
                      projectID:(NSString *)projectId
                       hostName:(NSString *)hostName
                environmentName:(NSString *)name
                       userName:(NSString *)username
                         useSSL:(BOOL)useSSL
                       delegate:(id<ABNotifierDelegate>)delegate
        installExceptionHandler:(BOOL)exception
           installSignalHandler:(BOOL)signal
              displayUserPrompt:(BOOL)display;

set 'displayUserPrompt' to NO will not display info.
