### ISSUE TITLE
Stack trace not showing application frames.

### ISSUE THREAD

**Issue by giantslogik** [airbrake/airbrake-ios#86]
The crash stack traces in the airbrake console , do not show the Application Stack frames.

For eg i see:
/usr/lib/system/libsystem_kernel.dylib:8 in __pthread_kill
/usr/lib/system/libsystem_c.dylib:140 in abort
/var/containers/Bundle/Application/1C73DFF8-4FD1-4943-ABB6-4311C397F590/My.app/
My: in -[PLCrashReporter generateLiveReportWithThread:]
/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation:644 in <redacted>
/usr/lib/libobjc.A.dylib:112 in <redacted>
/usr/lib/libc++abi.dylib:16 in <redacted>
/usr/lib/libc++abi.dylib:144 in __cxa_rethrow
/usr/lib/libobjc.A.dylib:44 in objc_exception_rethrow
/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation:560 in CFRunLoopRunSpecific
/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices:180 in GSEventRunModal
/System/Library/Frameworks/UIKit.framework/UIKit:684 in <redacted>
/System/Library/Frameworks/UIKit.framework/UIKit:208 in UIApplicationMain
/var/containers/Bundle/Application/1C73DFF8-4FD1-4943-ABB6-4311C397F590/My.app/My:88 in main
: in 0x1857dc5b8

I have followed the build settings advise from the github page:
Deployment Postprocessing: Off
Strip Debug Symbols During Copy: Off
Strip Linked Product: Off

**Comment by giantslogik** [comment]
On further investigation this is bug in airbrake-ios.
An exception handler in CFRunloop catches and rethrows a new exception.[https://stackoverflow.com/questions/13777446/ios-how-to-get-stack-trace-of-an-unhandled-stdexception]
PLCrashReporter already has the ability to get the stack off underlying exception. Airbrake-ios should get it from PLCrashReportExceptionInfo *_exceptionInfo;

**Comment by jocelynlih** [comment]
Thx for the finding, will take a look at this issue.

**Comment by giantslogik** [comment]
Jocelyn,
 Some further information. This may actually be a bug on the airbrake server api.
POST https://airbrake.io/api/v3/projects/PROJECT_ID/ios-reports?key=PROJECT_KEY

body json:
{
report: '...',
context : '...'
}

The report string  json sent by airbrake-ios contains the correct backtrace from PLCrashReportExceptionInfo*, this is in a part of the report text starting with
"Last Exception Backtrace:"

However the airbrake web console does not display this. It only displays the stack of crashed thread, which is useless for crashes in a RunLoop. 

I did not find a way to get the full report from web console or locate url returned by the above web API. (https://airbrake.io/locate/xxxxxxxxxxxxxxxx)

Also the full report string contains stacks for all threads, useful to debug multithreading issues, which also is not available from airbrake web dashboard.

**Comment by giantslogik** [comment]
[samplereport.txt](https://github.com/airbrake/airbrake-ios/files/1228757/samplereport.txt)

Here's a report that was sent to airbrake server. The stack trace of interest starts with:
Last Exception Backtrace:

The airbrake dashboard / website only shows the stack trace starting with:
Thread 0 Crashed:

There seems to be no way of getting the Last Exception Backtrace.

**Comment by giantslogik** [comment]
Have forked the code, and developed a workaround.
https://github.com/SimpleBillsDev/airbrake-ios
The last exception backtrace is converted to a pseudo  crashed thread, and a second crash report is sent  to airbrake server.
The Podfile can be changed to use the fork rather than the default.
`pod 'Airbrake-iOS', :git => 'https://github.com/SimpleBillsDev/airbrake-ios.git'`

**Comment by aledalgrande** [comment]
+1 this is making airbrake for iOS pretty much useless
